option domain-name "local";
option domain-name-servers 10.10.10.2;
default-lease-time 600;
max-lease-time 7200;
authoritative;

# For detecting client architecture
option arch code 93 = unsigned integer 16;

# Detect iPXE and chain to boot.ipxe script
if exists user-class and option user-class = "iPXE" {
  filename "http://10.1.40.151/ipxe/boot.ipxe";
} else {
  # UEFI clients
  if option arch = 00:07 or option arch = 00:09 {
    filename "http://10.1.40.151/ipxe/ipxe.efi";
  } else {
    # Legacy BIOS clients (if needed)
    filename "http://10.1.40.151/ipxe/ipxe.pxe";
  }
}

subnet 10.1.40.0 netmask 255.255.255.0 {
  range 10.1.40.220 10.1.40.240;
  option routers 10.1.40.1;
}

