#!/bin/bash
# Generate a Kea DHCPv4 configuration for hostdeployer, on stdout.
#
# One generator, two callers: install.sh writes the first configuration at
# bootstrap, and update_dhcp_config.sh regenerates it when an operator changes
# the network settings in the admin UI. They used to have a copy each, and the
# copies drifted -- the UEFI HTTP Boot class kept pointing at ipxe.efi in one
# of them after the boot chain moved to serving the ESXi loader directly, so
# saving anything in Settings quietly reverted the change.
#
# Writes nothing and touches no service: it prints a configuration and exits.
# Validating and installing it is the caller's job, because the two callers
# want different things -- one is bootstrapping, the other has a running
# server to roll back to.
#
# Usage:
#   kea-config.sh --interface ens192 --server-ip 10.0.0.2 \
#                 --subnet 10.0.0.0/24 --pool "10.0.0.100 - 10.0.0.200" \
#                 --gateway 10.0.0.1 --dns 10.0.0.53[,10.0.0.54] \
#                 [--domain local] [--lease-time 600]

set -euo pipefail

INTERFACE=""
SERVER_IP=""
SUBNET=""
POOL=""
GATEWAY=""
DNS=""
DOMAIN=""
LEASE_TIME=600
MAX_LEASE_TIME=7200

die() { printf 'kea-config.sh: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
    case "$1" in
        --interface)  INTERFACE="${2:-}";  shift 2 ;;
        --server-ip)  SERVER_IP="${2:-}";  shift 2 ;;
        --subnet)     SUBNET="${2:-}";     shift 2 ;;
        --pool)       POOL="${2:-}";       shift 2 ;;
        --gateway)    GATEWAY="${2:-}";    shift 2 ;;
        --dns)        DNS="${2:-}";        shift 2 ;;
        --domain)     DOMAIN="${2:-}";     shift 2 ;;
        --lease-time) LEASE_TIME="${2:-}"; shift 2 ;;
        *)            die "unknown option: $1" ;;
    esac
done

for required in INTERFACE SERVER_IP SUBNET POOL GATEWAY DNS; do
    [ -n "${!required}" ] || die "--${required,,} is required"
done

# Kea takes a comma-separated string; whitespace in it is a parse error.
DNS="${DNS// /}"

# Emitted as JSON string values, so anything that would need escaping is a
# malformed argument rather than something to quote around.
for value in "$INTERFACE" "$SERVER_IP" "$SUBNET" "$POOL" "$GATEWAY" "$DNS" "$DOMAIN"; do
    if [[ $value == *[\"\\]* || $value == *$'\n'* ]]; then
        die "arguments may not contain quotes, backslashes or newlines"
    fi
done

DOMAIN_OPTION=""
if [ -n "$DOMAIN" ]; then
    DOMAIN_OPTION="
                { \"name\": \"domain-name\", \"data\": \"$DOMAIN\" },"
fi

cat <<CONFIG
// Kea DHCPv4 configuration for hostdeployer.
//
// Generated by deploy/kea-config.sh on $(date '+%Y-%m-%d %H:%M:%S').
// Regenerated whenever the network settings change in the admin UI, so
// manual edits here are lost. Change them in Settings, or edit the generator.
//
// Validate with:  kea-dhcp4 -t /etc/kea/kea-dhcp4.conf
{
"Dhcp4": {
    // Bound explicitly. Listening on every interface would answer DHCP on
    // the office network as readily as on the provisioning one.
    "interfaces-config": {
        "interfaces": [ "$INTERFACE" ]
    },

    // The control socket is how kea-shell and kea-ctrl-agent change subnets,
    // pools and reservations at runtime, without rewriting this file.
    "control-socket": {
        "socket-type": "unix",
        "socket-name": "/run/kea/kea4-ctrl-socket"
    },

    "lease-database": {
        "type": "memfile",
        "lfc-interval": 3600,
        "name": "/var/lib/kea/kea-leases4.csv"
    },

    // Short leases: these addresses are handed to machines that are being
    // installed and will not want them for long.
    "valid-lifetime": $LEASE_TIME,
    "max-valid-lifetime": $MAX_LEASE_TIME,

    "loggers": [
        {
            "name": "kea-dhcp4",
            "output_options": [ { "output": "/var/log/kea/kea-dhcp4.log" } ],
            "severity": "INFO"
        }
    ],

    // -------------------------------------------------------------------
    // Client classification
    //
    // The order matters. iPXE must be matched before the generic UEFI
    // classes: a machine that has already chainloaded iPXE sends both
    // option 77 and its architecture code, so matching the UEFI branch
    // first hands it the loader again and it loops forever. That is what
    // the "not member('iPXE')" guards are for.
    //
    // Legacy BIOS (arch 0) is deliberately absent. ESXi 8 requires UEFI, so
    // there is no undionly.kpxe path to maintain.
    // -------------------------------------------------------------------
    "client-classes": [
        {
            // Set by iPXE itself once it is running (option 77, user-class).
            "name": "iPXE",
            "test": "substring(option[77].hex, 0, 4) == 'iPXE'",
            "boot-file-name": "http://$SERVER_IP/ipxe/boot.ipxe"
        },
        {
            // UEFI HTTP Boot (RFC 3925). The reply must echo the HTTPClient
            // vendor class back or the firmware ignores it.
            //
            // This branch goes straight to the ESXi loader: no iPXE, no TFTP.
            // /mboot.efi resolves which ESXi version the client is assigned
            // and streams that loader; mboot then fetches /boot.cfg beside
            // it, which the server renders for that host. Neither URL can
            // carry a MAC -- option 67 names one URL for the whole class --
            // so the server identifies the client by its address.
            "name": "UEFI-HTTP",
            "test": "not member('iPXE') and substring(option[60].hex, 0, 10) == 'HTTPClient'",
            "option-data": [
                { "name": "vendor-class-identifier", "data": "HTTPClient" }
            ],
            "boot-file-name": "http://$SERVER_IP/mboot.efi"
        },
        {
            // UEFI PXE (arch 7 = x64, 9 = EFI BC, 11 = arm64). The only
            // branch that needs a tftpd, because the firmware PXE stack has
            // no HTTP client. It exists for hardware that cannot HTTP Boot;
            // if none of yours is that old, drop this class and remove
            // tftpd-hpa.
            "name": "UEFI-PXE",
            "test": "not member('iPXE') and (option[93].hex == 0x0007 or option[93].hex == 0x0009 or option[93].hex == 0x000b)",
            "next-server": "$SERVER_IP",
            "boot-file-name": "ipxe.efi"
        }
    ],

    "subnet4": [
        {
            "id": 1,
            "subnet": "$SUBNET",
            "pools": [ { "pool": "$POOL" } ],

            // Advertised as siaddr; ipxe/boot.ipxe reads it as \${next-server}.
            "next-server": "$SERVER_IP",

            "option-data": [
                { "name": "routers", "data": "$GATEWAY" },$DOMAIN_OPTION
                { "name": "domain-name-servers", "data": "$DNS" }
            ],

            // Per-host reservations. The admin UI manages these through the
            // control socket rather than by rewriting this file, so anything
            // added here by hand survives only until the next regeneration.
            "reservations": [
            ]
        }
    ]
}
}
CONFIG
