#!/bin/bash
# Generate a Kea DHCPv4 configuration for hostdeployer, on stdout.
#
# The only place this configuration is written. install.sh calls it at
# bootstrap; after that, DHCP changes go through Kea's control API
# (lib/kea.php) rather than through this file at all.
#
# There is deliberately no static example of this file in the repository. There
# were two before -- a checked-in dhcp/kea-dhcp4.conf and a heredoc inside the
# update script -- and both drifted from each other, twice pointing UEFI HTTP
# Boot at the wrong loader. One generator has no copy to disagree with.
#
# Run it by hand to rebuild /etc/kea/kea-dhcp4.conf from scratch: after a bad
# hand edit, or when Kea will not start and so has no socket to talk to.
#
# Writes nothing and touches no service: it prints a configuration and exits.
# Validating and installing it is the caller's job.
#
# Usage:
#   kea-config.sh --interface ens192 --server-ip 10.0.0.2 \
#                 --subnet 10.0.0.0/24 --pool "10.0.0.100 - 10.0.0.200" \
#                 --gateway 10.0.0.1 --dns 10.0.0.53[,10.0.0.54] \
#                 [--domain local] [--lease-time 600]

set -euo pipefail

INTERFACE=""
SERVER_IP=""
SUBNET=""
POOL=""
GATEWAY=""
DNS=""
DOMAIN=""
LEASE_TIME=600
MAX_LEASE_TIME=7200

die() { printf 'kea-config.sh: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
    case "$1" in
        --interface)  INTERFACE="${2:-}";  shift 2 ;;
        --server-ip)  SERVER_IP="${2:-}";  shift 2 ;;
        --subnet)     SUBNET="${2:-}";     shift 2 ;;
        --pool)       POOL="${2:-}";       shift 2 ;;
        --gateway)    GATEWAY="${2:-}";    shift 2 ;;
        --dns)        DNS="${2:-}";        shift 2 ;;
        --domain)     DOMAIN="${2:-}";     shift 2 ;;
        --lease-time) LEASE_TIME="${2:-}"; shift 2 ;;
        *)            die "unknown option: $1" ;;
    esac
done

for required in INTERFACE SERVER_IP SUBNET POOL GATEWAY DNS; do
    [ -n "${!required}" ] || die "--${required,,} is required"
done

# Kea takes a comma-separated string; whitespace in it is a parse error.
DNS="${DNS// /}"

# Emitted as JSON string values, so anything that would need escaping is a
# malformed argument rather than something to quote around.
for value in "$INTERFACE" "$SERVER_IP" "$SUBNET" "$POOL" "$GATEWAY" "$DNS" "$DOMAIN"; do
    if [[ $value == *[\"\\]* || $value == *$'\n'* ]]; then
        die "arguments may not contain quotes, backslashes or newlines"
    fi
done

DOMAIN_OPTION=""
if [ -n "$DOMAIN" ]; then
    DOMAIN_OPTION="
                { \"name\": \"domain-name\", \"data\": \"$DOMAIN\" },"
fi

cat <<CONFIG
// Kea DHCPv4 configuration for hostdeployer.
//
// Generated by deploy/kea-config.sh on $(date '+%Y-%m-%d %H:%M:%S').
// Ordinary changes go through Kea's control API and are persisted with
// config-write, so hand edits here survive only until the next one. Change
// the network settings in the admin UI instead.
//
// Validate with:  kea-dhcp4 -t /etc/kea/kea-dhcp4.conf
{
"Dhcp4": {
    // Bound explicitly. Listening on every interface would answer DHCP on
    // the office network as readily as on the provisioning one.
    "interfaces-config": {
        "interfaces": [ "$INTERFACE" ]
    },

    // The control socket is how kea-shell and kea-ctrl-agent change subnets,
    // pools and reservations at runtime, without rewriting this file.
    "control-socket": {
        "socket-type": "unix",
        "socket-name": "/run/kea/kea4-ctrl-socket"
    },

    "lease-database": {
        "type": "memfile",
        "lfc-interval": 3600,
        "name": "/var/lib/kea/kea-leases4.csv"
    },

    // Short leases: these addresses are handed to machines that are being
    // installed and will not want them for long.
    "valid-lifetime": $LEASE_TIME,
    "max-valid-lifetime": $MAX_LEASE_TIME,

    "loggers": [
        {
            "name": "kea-dhcp4",
            "output_options": [ { "output": "/var/log/kea/kea-dhcp4.log" } ],
            "severity": "INFO"
        }
    ],

    // -------------------------------------------------------------------
    // Client classification
    //
    // The order matters. iPXE must be matched before the generic UEFI
    // classes: a machine that has already chainloaded iPXE sends both
    // option 77 and its architecture code, so matching the UEFI branch
    // first hands it the loader again and it loops forever. That is what
    // the "not member('iPXE')" guards are for.
    //
    // Legacy BIOS (arch 0) is deliberately absent. ESXi 8 requires UEFI, so
    // there is no undionly.kpxe path to maintain.
    // -------------------------------------------------------------------
    "client-classes": [
        {
            // Set by iPXE itself once it is running (option 77, user-class).
            "name": "iPXE",
            "test": "substring(option[77].hex, 0, 4) == 'iPXE'",
            "boot-file-name": "http://$SERVER_IP/ipxe/boot.ipxe"
        },
        {
            // UEFI HTTP Boot (RFC 3925). The reply must echo the HTTPClient
            // vendor class back or the firmware ignores it.
            //
            // This branch goes straight to the ESXi loader: no iPXE, no TFTP.
            // /mboot.efi resolves which ESXi version the client is assigned
            // and streams that loader; mboot then fetches /boot.cfg beside
            // it, which the server renders for that host. Neither URL can
            // carry a MAC -- option 67 names one URL for the whole class --
            // so the server identifies the client by its address.
            "name": "UEFI-HTTP",
            "test": "not member('iPXE') and substring(option[60].hex, 0, 10) == 'HTTPClient'",
            "option-data": [
                { "name": "vendor-class-identifier", "data": "HTTPClient" }
            ],
            "boot-file-name": "http://$SERVER_IP/mboot.efi"
        },
        {
            // UEFI PXE (arch 7 = x64, 9 = EFI BC, 11 = arm64). The only
            // branch that needs a tftpd, because the firmware PXE stack has
            // no HTTP client. It exists for hardware that cannot HTTP Boot;
            // if none of yours is that old, drop this class and remove
            // tftpd-hpa.
            "name": "UEFI-PXE",
            "test": "not member('iPXE') and (option[93].hex == 0x0007 or option[93].hex == 0x0009 or option[93].hex == 0x000b)",
            "next-server": "$SERVER_IP",
            "boot-file-name": "ipxe.efi"
        },
        {
            // The union of the three branches above. The subnet is bound to
            // this class, so a machine that is not network booting gets no
            // lease at all.
            //
            // Without it Kea answers every DHCPDISCOVER that reaches the
            // interface -- laptops, printers, anything -- because the classes
            // above only choose a boot file for a client that already holds a
            // lease; they do not decide who gets one. On a network that already
            // has a DHCP server that makes this one a rogue server racing it.
            //
            // Must be defined last: classes are evaluated in order, and
            // member() can only refer to a class already evaluated.
            "name": "PXE-CLIENTS",
            "test": "member('iPXE') or member('UEFI-HTTP') or member('UEFI-PXE')"
        }
    ],

    "subnet4": [
        {
            "id": 1,
            "subnet": "$SUBNET",
            "pools": [ { "pool": "$POOL" } ],

            // Only machines that are network booting. See PXE-CLIENTS above:
            // without this the pool is handed to whatever asks first.
            "client-class": "PXE-CLIENTS",


            // Advertised as siaddr; ipxe/boot.ipxe reads it as \${next-server}.
            "next-server": "$SERVER_IP",

            "option-data": [
                { "name": "routers", "data": "$GATEWAY" },$DOMAIN_OPTION
                { "name": "domain-name-servers", "data": "$DNS" }
            ],

            // Per-host reservations. Managed through the control socket, and
            // preserved across a network change -- keaUpdateNetwork() carries
            // them over rather than replacing the subnet wholesale.
            "reservations": [
            ]
        }
    ]
}
}
CONFIG
