#!/bin/bash
# Generate the nginx site for hostdeployer, on stdout.
#
# The only place this configuration is written. There used to be a static
# nginx.conf in the repository that install.sh copied and patched with sed, and
# that works exactly as long as every listener binds every address -- which is
# the thing this appliance must not do.
#
# hostdeployer sits on up to three networks and belongs on each of them
# differently:
#
#   admin network    the dashboard and the REST API, over TLS. Operators reach
#                    the appliance here and nowhere else.
#
#   deploy network   DHCP, TFTP and the boot chain over plain HTTP. The clients
#                    are firmware and a running installer, neither of which can
#                    hold a credential, so nothing here is authenticated -- and
#                    that is precisely why the admin interface must not answer
#                    on this address. See docs/network-segmentation.md.
#
#   iLO/iDRAC        no listener at all. Traffic to the management cards is
#                    outbound, opened by the admin UI when it scans or toggles
#                    secure boot. Nothing on the appliance listens there, so
#                    nothing here configures it.
#
# A generator rather than a template because the shape changes, not just the
# addresses: with one address the boot listener also redirects browsers to TLS,
# and with two it must not -- a redirect from the deploy network would announce
# where the admin interface lives. Two static files would drift; sed cannot add
# and remove server blocks.
#
# IPv4 only, deliberately. The static file this replaced also carried
# "listen [::]:80" and "listen [::]:443", which bound every IPv6 address on the
# machine -- including ones on networks the admin interface has no business
# answering on, which is the finding this exists to fix. Kea here is DHCPv4 and
# every address the appliance handles is v4, so there is nothing to serve over
# v6 that is not reachable over v4.
#
# Writes nothing and touches no service: it prints a configuration and exits.
# Validating and installing it is the caller's job.
#
# Usage:
#   nginx-config.sh --deploy-ip 10.20.0.2 [--admin-ip 10.10.0.2]
#                   [--admin-allow 10.10.0.0/24] [--fpm-socket PATH] [--root DIR]
#
#   --deploy-ip     address the boot chain answers on
#   --admin-ip      address the dashboard and API answer on. Defaults to
#                   --deploy-ip, which is the single-interface installation.
#   --admin-allow   network allowed to reach the dashboard and API. Repeatable.
#                   Omit to allow any source that reaches the address.
#   --fpm-socket    php-fpm unix socket (default /run/php/php8.4-fpm.sock)
#   --root          deployment root (default /srv/autodeploy)

set -euo pipefail

DEPLOY_IP=""
ADMIN_IP=""
ADMIN_ALLOW=()
FPM_SOCKET="/run/php/php8.4-fpm.sock"
ROOT="/srv/autodeploy"

die() { printf 'nginx-config.sh: %s\n' "$*" >&2; exit 1; }

while [ $# -gt 0 ]; do
    case "$1" in
        --deploy-ip)    DEPLOY_IP="${2:-}";   shift 2 ;;
        --admin-ip)     ADMIN_IP="${2:-}";    shift 2 ;;
        --admin-allow)  ADMIN_ALLOW+=("${2:-}"); shift 2 ;;
        --fpm-socket)   FPM_SOCKET="${2:-}";  shift 2 ;;
        --root)         ROOT="${2:-}";        shift 2 ;;
        *)              die "unknown option: $1" ;;
    esac
done

[ -n "$DEPLOY_IP" ] || die "--deploy-ip is required"
ADMIN_IP="${ADMIN_IP:-$DEPLOY_IP}"

# Emitted into a configuration nginx parses, so anything that would need
# quoting is a malformed argument rather than something to quote around.
for value in "$DEPLOY_IP" "$ADMIN_IP" "$FPM_SOCKET" "$ROOT" ${ADMIN_ALLOW+"${ADMIN_ALLOW[@]}"}; do
    case "$value" in
        *[\;\{\}\"\'\$]*|*$'\n'*) die "arguments may not contain ; { } quotes, \$ or newlines" ;;
    esac
done

# One address means one network, so the boot listener is also where an operator
# arrives and it should send them to TLS. Two addresses mean the boot listener
# is on a network the admin interface is not on, and a redirect there would
# point at an address the asker has no business knowing.
SPLIT=0
[ "$ADMIN_IP" != "$DEPLOY_IP" ] && SPLIT=1

ACCESS_RULES=""
if [ ${#ADMIN_ALLOW[@]} -gt 0 ]; then
    ACCESS_RULES=$'\n    # Second lock. The listen address above is what keeps the packets from\n'
    ACCESS_RULES+=$'    # arriving; this is what applies if that binding is ever widened, or if\n'
    ACCESS_RULES+=$'    # the traffic is routed here from somewhere else.\n'
    for network in "${ADMIN_ALLOW[@]}"; do
        ACCESS_RULES+="    allow $network;"$'\n'
    done
    ACCESS_RULES+=$'    allow 127.0.0.1;\n    deny  all;\n'
fi

cat <<CONFIG
# nginx site for the ESXi auto-deployment server.
#
# Generated by deploy/nginx-config.sh on $(date '+%Y-%m-%d %H:%M:%S').
# Re-generate rather than editing: install.sh writes this file, and a hand
# edit survives only until the next run.
#
# Layout on disk:
#   $ROOT/www        PHP endpoints and the admin dashboard
#   $ROOT/ipxe       ipxe.efi and boot.ipxe
#   $ROOT/esxi/<ver> extracted ESXi installer media
#   $ROOT/config     configuration and credentials (NOT served)
#   $ROOT/logs       log files (NOT served)
#
# Addresses:
#   boot chain   $DEPLOY_IP:80
#   dashboard    $ADMIN_IP:443
CONFIG

if [ "$SPLIT" = 1 ]; then
    cat <<CONFIG
#
# These are different networks. The boot chain is unauthenticated by necessity
# -- its clients are firmware -- so the admin interface is bound away from it
# rather than merely protected on it.
CONFIG
fi

cat <<CONFIG

upstream autodeploy_php {
    server unix:$FPM_SOCKET;
}

# ---------------------------------------------------------------------------
# Deploy network, port 80: everything the boot chain needs, and nothing else.
#
# UEFI HTTP Boot and iPXE as commonly built have no usable trust store, so the
# boot artefacts must stay reachable over plain HTTP. Every endpoint below is
# unauthenticated apart from the boot token the server itself issued, because
# the caller is firmware and then an installer.
# ---------------------------------------------------------------------------
server {
    listen $DEPLOY_IP:80 default_server;
    server_name _;

    access_log /var/log/nginx/autodeploy-access.log;
    error_log  /var/log/nginx/autodeploy-error.log;

    root $ROOT/www;

    # Installers do not POST anything large.
    client_max_body_size 2m;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;

    # -- Boot artefacts -----------------------------------------------------

    # iPXE binaries and the static chain script.
    location /ipxe/ {
        alias $ROOT/ipxe/;
        autoindex off;
    }

    # ESXi installer media. The version is bounded to a single path segment and
    # nginx normalises the URI before matching, so ../ cannot escape the alias.
    location ~ ^/esxi/(?<esxi_version>[A-Za-z0-9._-]+)/(?<esxi_file>.+)\$ {
        alias $ROOT/esxi/\$esxi_version/\$esxi_file;
        # A directory listing of the installer tree exposes the whole image to
        # anyone on the provisioning VLAN.
        autoindex off;
    }

    # Dynamic iPXE script generator.
    location = /boot.ipxe.php {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/boot.ipxe.php;
    }

    # Dynamic kickstart generator.
    location = /ks.cfg {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/generate_kickstart.php;
    }

    # The ESXi loader for UEFI HTTP Boot. Resolves the client's assigned
    # version, which DHCP option 67 cannot express since it names one URL for
    # the whole class.
    location = /mboot.efi {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/mboot.efi.php;
    }

    # mboot fetches boot.cfg from the directory it was loaded from, so this has
    # to sit beside /mboot.efi in the URL space.
    location = /boot.cfg {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/boot.cfg.php;
    }

    location = /boot.cfg.php {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/boot.cfg.php;
    }

    # Progress beacon from %firstboot, before the completion callback.
    location = /progress.php {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/progress.php;
    }

    # Deployment completion callback from %firstboot.
    location = /deployment_complete.php {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/deployment_complete.php;
    }

    # The kickstart templates call the callback under /admin/; keep that URL
    # working without exposing the rest of /admin/ over plain HTTP.
    location = /admin/deployment_complete.php {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/deployment_complete.php;
    }

CONFIG

if [ "$SPLIT" = 1 ]; then
    cat <<'CONFIG'
    # The admin interface is not on this network and this listener does not say
    # where it is. A redirect would: it would hand every scanner on the deploy
    # VLAN the hostname to aim at.
    location / { return 404; }
}
CONFIG
else
    cat <<'CONFIG'
    # One address, so this is also where an operator arrives. Send them to TLS:
    # a session cookie and a login form must never cross port 80.
    location /admin/ {
        return 301 https://$host$request_uri;
    }

    location = / {
        return 301 https://$host/admin/;
    }

    # Everything else on port 80 is not part of the boot chain.
    location / { return 404; }
}
CONFIG
fi

if [ "$SPLIT" = 1 ]; then
    cat <<CONFIG

# ---------------------------------------------------------------------------
# Admin network, port 80: nothing but a nudge to TLS, for an operator who
# typed the address without a scheme.
# ---------------------------------------------------------------------------
server {
    listen $ADMIN_IP:80;
    server_name _;
$ACCESS_RULES
    location / {
        return 301 https://\$host\$request_uri;
    }
}
CONFIG
fi

cat <<CONFIG

# ---------------------------------------------------------------------------
# Admin network, port 443: the dashboard and the REST API.
# ---------------------------------------------------------------------------
server {
    listen $ADMIN_IP:443 ssl default_server;
    http2 on;
    server_name _;
$ACCESS_RULES
    access_log /var/log/nginx/autodeploy-admin-access.log;
    error_log  /var/log/nginx/autodeploy-admin-error.log;

    # Replace with a certificate for this host. A self-signed certificate is
    # acceptable on an isolated provisioning network; browsers are the only
    # clients here, and they can be told to trust it once.
    ssl_certificate     /etc/ssl/autodeploy/server.crt;
    ssl_certificate_key /etc/ssl/autodeploy/server.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:autodeploy:10m;
    ssl_session_timeout 10m;

    root $ROOT/www;
    index admin_dashboard.php;

    # ESXi ISOs are several gigabytes and are uploaded through this listener.
    # php.ini needs raising to match: upload_max_filesize and post_max_size.
    client_max_body_size 16g;

    # An ISO takes minutes to arrive over a slow link; the stock 60s read
    # timeout drops the connection part way through.
    client_body_timeout 30m;

    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy same-origin always;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; frame-ancestors 'none'" always;

    location = / {
        return 301 /admin/;
    }

    # -- REST API ------------------------------------------------------------
    #
    # Deliberately only on the TLS listener. The API authenticates with a
    # bearer token, and a token crossing port 80 is a token on the wire.
    # The capture is what puts the route in PATH_INFO without the /api prefix.
    location ~ ^/api(/.*)\$ {
        include        fastcgi_params;
        fastcgi_pass   autodeploy_php;
        fastcgi_param  SCRIPT_FILENAME $ROOT/www/api.php;
        fastcgi_param  PATH_INFO       \$1;

        # fastcgi_params does not forward Authorization, and php-fpm cannot see
        # the header without it, so every request would arrive anonymous.
        fastcgi_param  HTTP_AUTHORIZATION \$http_authorization;

        # Hashing and extracting a multi-gigabyte image outlasts the default.
        fastcgi_read_timeout 30m;
        fastcgi_send_timeout 30m;
    }

    location /admin/ {
        alias $ROOT/www/;
        index admin_dashboard.php;

        # Never serve backups, editor leftovers or anything but PHP/static
        # assets out of the application directory.
        location ~* \.(bak|php_bak|json|log|sql|swp|orig|dist|inc)\$ {
            deny all;
        }

        # Do not hand .py helper scripts to clients as source.
        location ~* \.py\$ {
            deny all;
        }

        location ~ \.php\$ {
            include        fastcgi_params;
            fastcgi_pass   autodeploy_php;
            fastcgi_param  SCRIPT_FILENAME \$request_filename;
            # Refuse /foo.jpg/bar.php style path-info attacks.
            fastcgi_split_path_info ^(.+\.php)(/.*)\$;
            fastcgi_param  PATH_INFO \$fastcgi_path_info;
        }
    }

    # config/ and logs/ live outside this root, but block the paths anyway in
    # case the root is ever moved.
    location ~ ^/(config|logs|lib|scripts)/ {
        deny all;
    }

    location / {
        return 404;
    }
}
CONFIG
